version: '2'
services:
  db:
    build:
      context: .
      dockerfile: mysql.Dockerfile
      args:
        LORIS_VERSION: ${LORIS_VERSION}
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql_password
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password
    secrets:
      - mysql_password
      - mysql_root_password
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
  couchdb:
    image: couchdb:3
    volumes:
      - ./couchdb_config.ini:/opt/couchdb/etc/local.ini
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
  web:
    build:
      context: .
      dockerfile: loris.Dockerfile
      args:
        LORIS_VERSION: ${LORIS_VERSION}
    ports:
      - "8080:80"
    environment:
      # - LORIS_DB_CONFIG=/app/test/config.xml
      - LORIS_HOST=localhost
      - LORIS_ADMIN_USER=${LORIS_ADMIN_USER}
      - LORIS_ADMIN_PASSWORD_FILE=/run/secrets/loris_admin_password
      - MYSQL_HOST=db
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql_password
      - COUCHDB_HOST=couchdb
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
      couchdb:
        condition: service_started
    secrets:
      - mysql_password
      - mysql_root_password
      - loris_admin_password

secrets:
  mysql_password:
    file: ./secrets/mysql_password.txt
  mysql_root_password:
    file: ./secrets/mysql_root_password.txt
  loris_admin_password:
    file: ./secrets/loris_admin_password.txt