services:
  db:
    build:
      context: ./loris-mysql
      dockerfile: mysql.Dockerfile
      args:
        LORIS_SOURCE: ${LORIS_SOURCE}
        LORIS_VERSION: ${LORIS_VERSION}
    platform: linux/amd64
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql_password
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password
    secrets:
      - mysql_password
      - mysql_root_password
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
  web:
    build:
      context: ./loris-mri
      dockerfile: loris-mri.Dockerfile
      args:
        LORIS_SOURCE: ${LORIS_SOURCE}
        LORIS_VERSION: ${LORIS_VERSION}
        LORIS_BASE: ${LORIS_BASE}
    platform: linux/amd64
    ports:
      - "8080:80"
    volumes:
      - loris-projects:/var/www/loris/project
      - /Users/gabriel.schubiner/Documents/philani-code/data/linst:/etc/loris_instruments:ro
    environment:
      - LORIS_ADMIN_USER=${LORIS_ADMIN_USER}
      - MYSQL_HOST=db
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql_password
      - LORIS_ADMIN_PASSWORD_FILE=/run/secrets/loris_admin_password
      - LORIS_HOST=localhost
      - LORIS_PORT=8080
      - LORIS_EMAIL=${LORIS_EMAIL}
      - SITE_NAME=Philani
      - SITE_ALIAS=PHI
      - MRI_ALIAS=PHI
      - STUDY_SITE_YN=Y
      - VISIT_NAME=V1
      - VISIT_LABEL=V1
      - WINDOW_MIN_DAYS=0
      - WINDOW_MAX_DAYS=100
      - OPTIMUM_MIN_DAYS=40
      - OPTIMUM_MAX_DAYS=60
      - WINDOW_MIDPOINT_DAYS=50 
    depends_on:
      db:
        condition: service_healthy
    secrets:
      - mysql_password
      - mysql_root_password
      - loris_admin_password

volumes:
  loris-projects:

secrets:
  mysql_password:
    file: ./secrets/mysql_password.txt
  mysql_root_password:
    file: ./secrets/mysql_root_password.txt
  loris_admin_password:
    file: ./secrets/loris_admin_password.txt