services:
  db:
    image: mysql:latest
    # build:
    #   context: ./loris-mysql
    #   dockerfile: loris-mysql.Dockerfile
    #   args:
    #     LORIS_SOURCE: ${LORIS_SOURCE}
    #     LORIS_VERSION: ${LORIS_VERSION}
    platform: linux/amd64
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password
    secrets:
      - mysql_root_password
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
  web:
    image: loris:latest
    # build:
    #   context: ./loris-mri
    #   dockerfile: loris-mri.Dockerfile
    #   args:
    #     LORIS_SOURCE: ${LORIS_SOURCE}
    #     LORIS_VERSION: ${LORIS_VERSION}
    #     LORIS_BASE: ${LORIS_BASE}
    platform: linux/amd64
    ports:
      - "8080:80"
    volumes:
      - loris-projects:/var/www/loris/project
      - ${LORIS_LOCAL_INST_DIR:-./local_instruments}:/etc/loris_instruments:ro
    environment:
      # Admin config
      - LORIS_ADMIN_USER=${LORIS_ADMIN_USER}
      - LORIS_ADMIN_PASSWORD_FILE=/run/secrets/loris_admin_password
      # Server config
      - LORIS_HOST=localhost
      - LORIS_PORT=8080
      - PROJECT_NAME=loris
      - MANUAL_PSCID_GENERATION=True
      # DB config
      - MYSQL_HOST=db
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql_password
      # Site config
      - SITE_NAME=Philani
      - SITE_ALIAS=PHI
      - MRI_ALIAS=PHI
      - STUDY_SITE_YN=Y
      # Visit config
      - VISIT_LABELS=T1 T2
      - WINDOW_MIN_DAYS=0
      - WINDOW_MAX_DAYS=100
      - OPTIMUM_MIN_DAYS=40
      - OPTIMUM_MAX_DAYS=60
      - WINDOW_MIDPOINT_DAYS=50 
      # Cohort config
      # Cohort Labels listed here will be connected to:
      # - Project specified in PROJECT_NAME
      # - Visit Labels specified in VISIT_LABELS
      - COHORT_LABELS=Control
      # Default instrument / battery config
      - DEFAULT_TEST_AGE_MIN_DAYS=1095
      - DEFAULT_TEST_AGE_MAX_DAYS=5840
      - DEFAULT_TEST_STAGE=Approved
      - INSTALL_INSTRUMENT_BATTERY=True
      - DEFAULT_COHORT=Control
      # Email / SMTP config
      - LORIS_EMAIL=${LORIS_EMAIL}
      - SMTP_PASSWORD_FILE=/run/secrets/smtp_password
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_TLS=True
      # Database params
      # CREATE_DB required for RDS, not for compose MySQL container that creates DB and user on start
      - CREATE_DB=True
      - INSTALL_DB=True
      # DEBUG flag
      # - DEBUG_CONTAINER=True
    depends_on:
      db:
        condition: service_healthy
    secrets:
      - mysql_password
      - mysql_root_password
      - loris_admin_password
      - smtp_password

volumes:
  loris-projects:

secrets:
  mysql_password:
    file: ./secrets/mysql_password.txt
  mysql_root_password:
    file: ./secrets/mysql_root_password.txt
  loris_admin_password:
    file: ./secrets/loris_admin_password.txt
  smtp_password:
    file: ./secrets/smtp_password.txt